export const NewDossierModel = {
  name: "",
  produit: "",
  origin: "",
  destination: "",
  superviseur: "",
  agent_operant: "",
  agent_declarant: "",
  agent_terrain: "",
  agent_finance: "",
  client: "",
  superviseur_name: "",
  agent_operant_name: "",
  agent_declarant_name: "",
  agent_terrain_name: "",
  agent_finance_name: "",
  client_name: "",
  prix_traitement: 0,
  taxe: 0,
  facturation: 0,
};

export const SteppedDossierModel = {
  name: "",
  produit: "",
  origin: "",
  destination: "",
  supervisuer: "",
  agent_operant: "",
  agent_declarant: "",
  agent_terrain: "",
  agent_finance: "",
  client: "",
  superviseur_name: "",
  agent_operant_name: "",
  agent_declarant_name: "",
  agent_terrain_name: "",
  agent_finance_name: "",
  client_name: "",
  nbrcolis: "",
  company: "",
  poid: "",
  nature: "",
  numero_enr_douane: "",
  date_enr_douane: "",
  prix_traitement: 0,
  boxe: "",
  emplacement: "",
  taxe: 0,
  facturation: 0,
};
